{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sovereign-trade.serviceAccountName" . }}
  labels:
    {{- include "sovereign-trade.labels" . | nindent 4 }}
{{- end }}
